# jekyll serve --baseurl '' --host 0.0.0.0
baseurl: breitenberg-eichsfeld.de

#collections:
#  keramische_arbeiten:
#    output: true
#  content_posts:
#    output: true
#  news:
#    output: true


# https://jekyllrb.com/docs/configuration/markdown/
# https://stackoverflow.com/questions/28294959/jekyll-kramdown-how-to-center-text
kramdown:
  input: Kramdown